apiVersion: v1
data:
  prometheus.yaml.gz: H4sIAAAAAAAA/+ydUXPiNhDH3/kUmpt7yF3HcXL30vE9daZ9a6/3DTRCXkBBSJqVTJPp9Lt3LGywCU4wB8SQfQPb2l2trN/fFhtlqu1Y6GzEGCyFLkRQ1nBlAuBS6Ix9vfMjxrxE4eDZYXgMgEZorsUYtC+NMObQLiDMoPAZy2EiCh3ShTUqWFRmmmxOJ9YBNr5vteYITispMvbx5sffv/Pvv/31x6cRFhr4RGnw2ShhKQSZbpqk5VnfOJDs5Tgpm0WbyV36+fZJLPSo6rG0ZqKm0deDHXMjFrBXr4QGDAthxBQwvRsxNrPGYp0nNhHaw4ixeTEGNBDAc59vnDGWMLQaMgYmd1aZsEpO6d47IaFKdXWk/pLUkY0YW0BAJT13IswyllZfR4whxCDazoQshz1jcwAXjXlboITWuCaM8wUEwZtBAy5VfR0XbtUYYQqPGdvKiQi2nZcjekbQIGJG1943g3NEPx70hFeWm84+BCzgw085qkeaO4sh3mhNB//AOFrva0zkOYL3PAicQuBzZfLejdaxeHAiDmPGvjWD+25z+HZz+/lTddBpIWEBJmTs47/3/8Wjla0YeMaMzWG4/flh837dcTbv05v1NN6Vmca5vQ3WN+m6Z22b1ek+Fp3Nu6z17OwrsT3YcWeak61r6wF93qCcHn0J7VQZ2hvh2csZlIHOQnBl46B9ZX91tTIeZIHA/Vw5vgRUk6dNXIxJEUUwY+lSYIqFST1IhODTTcy3yqZV9oWUtjAhleJWYqhu/rLzVb42jUaMjUEgIA92DuYgL7HlaaVG2oWzBtb3Qpy36yE9oiOHdqlyaNG+la1TEb++MwbKSGI+Mf80zD8CD7rcxZG+uf2le5T3l5zV/OwpOtIi5MafUXJKe4l/8gEWF4L2Pd4iqjRexAvE65RPNi9nA4UjwZ5gPyDYP9jxn+WHs7J+PUt7In+KYiKMeE+LQM2TynJlfBBGnn515rnrbdxWg3FCoB8wFYnlxPJrYPm+NK172BOk8UlWWhPQag2YnH91/SqfpTvSSs/WxGPi8UXz+PqfrSO7IMicROAIIlAmkrBP2CfsE/aHj32H9vGJuH8E7sdMEvgJ/AR+Av/wwe/lDPJC08rPUeC/ziYJAAkACQAJwAUIQBABags7RCBgcdqfVd/rr6fPs39imA8XegRxgviAIP7C3D0X0g9BuYZwPn63n+EPK8CvQvv5+vtLeIWY/+q3XyOqQTt12Ts9xBP/if8HTtWzFb/vOUvXFYic74ivecGhEnL/NhKyu7oylSJfKh//PpREhkSGRIZEhkTm8kXmy6BExqEdgyeJIYkhiSGJIYm5Con5OiiJQVjlIl3eC+1m4p7UhtSG1IbUhtTmotWmnFIJPJYceaPNj96k7KnV7SsodiLYE+wJ9gOuczqwxKkuz7y+wqYOMK/rUesPVwBnKl4iMr9HMp+yYKixzfM72kvnNWi2ts8ePjZpO2XCM+F56Hgup0fcqV2ZuLAbP/MXQRdP5Wg7gFVv5l8bq3aZqYzEdQ6HMFGPGUtXN1NjpTke6CR7F9t30X2L723CMyac4ktAH3u0/FJ15Vmvd3JpJ5n2HMMdlH3xPwocIYYOPrYI+X8AAAD//+yoExsbYgAA
kind: Secret
metadata:
  annotations:
    generated: "true"
  creationTimestamp: "2020-12-18T12:01:18Z"
  labels:
    managed-by: prometheus-operator
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:prometheus.yaml.gz: {}
      f:metadata:
        f:annotations:
          .: {}
          f:generated: {}
        f:labels:
          .: {}
          f:managed-by: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"b9b1b279-6036-45ac-9595-7888527d26c6"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:type: {}
    manager: operator
    operation: Update
    time: "2020-12-18T12:01:18Z"
  name: prometheus-monitoring-prometheus-oper-prometheus
  namespace: default
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: monitoring-prometheus-oper-prometheus
    uid: b9b1b279-6036-45ac-9595-7888527d26c6
  resourceVersion: "25052"
  selfLink: /api/v1/namespaces/default/secrets/prometheus-monitoring-prometheus-oper-prometheus
  uid: 97a28f40-22ef-4b58-a8f9-258d4f35ece7
type: Opaque
